name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      # Step 2: Log in Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t pcarlos/pgimporter_app:rc .
      # Step 4: Tag the Docker Image
      - name: Tag Docker Image
        run: |
          docker tag pcarlos/pgimporter_app pcarlos/pgimporter_app:rc
      # Step 5: Push the Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push pcarlos/pgimport_app:rc